### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by ashokyadav006**
Added below changes.
1. Showing map on full screen without scrollbars
2. moved toolbar icons in the middle
3. hiding zoom in zoom out buttons.

Will work on other changes in different commits meanwhile test it in your system and different browsers if everything works fine.

### CODE REVIEW

**Comment by Zia-** [comment]
"Fixed the map to fit the page" and "left side bar minimized" are not working. I am not merging the requests now. Plz update it. Below the screen shot after page reload. The left side bar was full for a fraction of second and got then reduced, leaving right section blank. 
screen shot 2016-05-02 at 11 39 20

**Comment by Zia-** [comment]
[screenrecord_CLIPCHAMP_keep.mp4.zip](https://github.com/Zia-/TUIK_page/files/244734/screenrecord_CLIPCHAMP_keep.mp4.zip)

**Comment by ashokyadav006** [comment]
Check now if it works fine. For me it looks fine.. I am attaching screenshot .

**Comment by Zia-** [comment]
Abe map poora screen nai le raa ab bhi. Aur left nav bar bhi kabhi kabhi expanded hoke fir shrink ho raha hai. Video dekh zara. 
[screenrecord.zip](https://github.com/Zia-/TUIK_page/files/244866/screenrecord.zip)

**Comment by Zia-** [comment]
ye vaala dell pc pe hai. ispe bhi maximize ho jaa raha hai side bar
screentuik

**Comment by ashokyadav006** [comment]
Check this video... it works perferctly fine in chrome & firefox both..
[tuik.ogv.zip](https://github.com/Zia-/TUIK_page/files/244876/tuik.ogv.zip)

**Comment by ashokyadav006** [comment]
sidebar_menu.js me main he height calculate kar raha hoon just check kahin vo galat calculate to nahi ho rahi tere system me.. ya fir jo calculate ho rahi hai vo apply ho rahi hai ki nahi...just put a breakpoint there

**Comment by Zia-** [comment]
ek kaam kar, apna browser ko badaa karde thoda, itna ki side bar ke saare buttons aa jaaein.. then try kar.
btw tere mein bhi to side bar maximize hoke fir reduce ho raha hai!

**Comment by ashokyadav006** [comment]
isse badi screen nahi hai meri

**Comment by ashokyadav006** [comment]
vo bada hokar chota ho raha par usse map pe kuch effect nahi padega.. muje bhi samaj nahi aa raha aisa kyun behave kar raha vo.

**Comment by Zia-** [comment]
haan, vo bada hoke chota ho raha hi  main dekh raha abhi

**Comment by ashokyadav006** [comment]
ek baar debug kar i'm sure height set karne ka hi kuch issue hai

**Comment by Zia-** [comment]
PR bheja hai. Left side bar ab sahi lag raha hai. Behaving normally.

**Comment by Zia-** [comment]
Merge kar apne mein. Baaki height ka kaise debug karu? Kya value check karni hai log mein?

**Pull request merged**
